FROM mcr.microsoft.com/dotnet/sdk:5.0 as base
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Development
ENV TZ=Europe/Paris

WORKDIR /app
EXPOSE 80

COPY . .

RUN dotnet restore

ENTRYPOINT [ "dotnet", "watch", "run", "--no-launch-profile" ]
