FROM mcr.microsoft.com/dotnet/sdk:5.0 as base
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Development
ENV TZ=Europe/Paris

WORKDIR /app

COPY worker.csproj .

RUN dotnet restore


FROM base as dev
WORKDIR /app

COPY --from=base . .
COPY . .

CMD [ "dotnet", "watch", "run", "--no-launch-profile" ]
